combos_map = {
    ('pos','high','high'): 'energized-confidence',
    ('pos','high','mid'): 'enthusiastic-drive',
    ('pos','high','low'): 'delighted-surrender',
    ('pos','mid','high'): 'steady-resolve',
    ('pos','mid','mid'): 'warm-engagement',
    ('pos','mid','low'): 'receptive-warmth',
    ('pos','low','high'): 'quiet-authority',
    ('pos','low','mid'): 'gentle-warmth',
    ('pos','low','low'): 'gentle-acceptance',
    ('neg','high','high'): 'combative-defiance',
    ('neg','high','mid'): 'agitated-resistance',
    ('neg','high','low'): 'urgent-distress',
    ('neg','mid','high'): 'guarded-tension',
    ('neg','mid','mid'): 'steady-discomfort',
    ('neg','mid','low'): 'vulnerable-frustration',
    ('neg','low','high'): 'cold-withdrawal',
    ('neg','low','mid'): 'quiet-resignation',
    ('neg','low','low'): 'quiet-sadness',
    ('neutral','high','high'): 'focused-flow',
    ('neutral','high','mid'): 'alert-readiness',
    ('neutral','high','low'): 'restless-searching',
    ('neutral','mid','high'): 'grounded-awareness',
    ('neutral','mid','mid'): 'balanced-presence',
    ('neutral','mid','low'): 'uncertain-drift',
    ('neutral','low','high'): 'settled-composure',
    ('neutral','low','mid'): 'passive-observation',
    ('neutral','low','low'): 'flat-numbness',
}
print(f'Total: {len(combos_map)} of 27')
for k,v in combos_map.items():
    print(f'  {k} -> {v}')
