#!/usr/bin/env python3
"""Batch convert top emotional words from NRC VAD Lexicon to MeTTa PB-Vec atoms.
Reads the NRC-VAD-Lexicon-v2.1.txt and outputs native MeTTa atoms.
Usage: python3 vad_batch_converter.py [num_words] [output_file]
"""
import sys

LEXICON_PATH = '/tmp/NRC_VAD_Lexicon_v2.1/NRC-VAD-Lexicon-v2.1.txt'

# Words with highest emotional significance: extremes in V, A, or D
def emotional_significance(v, a, d):
    return abs(v - 0.5) + abs(a - 0.5) + abs(d - 0.5)

def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 100
    outfile = sys.argv[2] if len(sys.argv) > 2 else '/tmp/vad_lexicon_top100.metta'
    entries = []
    with open(LEXICON_PATH, 'r') as f:
        header = True
        for line in f:
            if header:
                header = False
                continue
            parts = line.strip().split('\t')
            if len(parts) >= 4:
                word = parts[0].lower().replace(' ', '-').replace(chr(39), '')
                try:
                    v, a, d = float(parts[1]), float(parts[2]), float(parts[3])
                    sig = emotional_significance(v, a, d)
                    entries.append((word, v, a, d, sig))
                except ValueError:
                    continue
    entries.sort(key=lambda x: -x[4])
    top = entries[:n]
    with open(outfile, 'w') as f:
        f.write(';; NRC VAD Lexicon - Top {} emotionally significant words as MeTTa PB-Vec atoms\n'.format(n))
        f.write(';; Generated by vad_batch_converter.py\n')
        f.write(';; Format: (= (vad-lookup word) (PB-Vec valence arousal dominance))\n\n')
        for word, v, a, d, sig in top:
            f.write('(= (vad-lookup {}) (PB-Vec {:.3f} {:.3f} {:.3f}))\n'.format(word, v, a, d))
    print('Wrote {} atoms to {}'.format(len(top), outfile))

if __name__ == '__main__':
    main()
