import os
os.makedirs('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates', exist_ok=True)
lines = [
    ';; lib_web_detect.metta -- ClarityClaw causal web pattern detection',
    ';; Detects convergence, divergence, and cycles in implication webs',
    '',
    ';; --- Type declarations ---',
    '(: convergence-result Type)',
    '(: divergence-result Type)',
    '(: chain-result Type)',
    '(: converge? (-> Atom Atom Atom))',
    '(: diverge? (-> Atom Atom Atom))',
    '(: causal-chain (-> Atom Atom Atom))',
    '(: support-merge (-> Atom Atom Atom))',
    '(: weak-link (-> Atom Atom Atom))',
    '(: amplified? (-> Atom Atom Atom Atom))',
    '',
    ';; --- Convergence detector ---',
    '(= (converge? (==> $a $c) (==> $b $c))',
    '   (convergence $c ($a $b)))',
    '',
    ';; --- Divergence detector ---',
    '(= (diverge? (==> $a $b) (==> $a $c))',
    '   (divergence $a ($b $c)))',
    '',
    ';; --- Causal chain via deduction ---',
    '(= (causal-chain $ab $bc)',
    '   (|- $ab $bc))',
    '',
    ';; --- Weakest link ---',
    '(= (weak-link (stv $f1 $c1) (stv $f2 $c2))',
    '   (if (< $c1 $c2) (stv $f1 $c1) (stv $f2 $c2)))',
    '',
    ';; --- Amplification detector ---',
    '(= (amplified? (stv $f1 $c1) (stv $f2 $c2) (stv $fr $cr))',
    '   (if (and (> $cr $c1) (> $cr $c2)) True False))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates/lib_web_detect.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
