import os
os.makedirs('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates', exist_ok=True)
lines = [
    ';; lib_resonance.metta -- ClarityClaw gap resonance detection',
    ';; Detects what is absent but expected - absence as signal',
    ';; Pure MeTTa, no Python',
    '',
    ';; --- Type declarations ---',
    '(: gap-signal Type)',
    '(: resonance-level Type)',
    '(: curiosity-action Type)',
    '(: expect-from (-> Atom Atom Atom))',
    '(: gap? (-> Atom Atom Atom))',
    '(: resonance (-> Atom Number Atom))',
    '(: missing-link? (-> Atom Atom Atom))',
    '(: curiosity-target (-> Atom Atom Atom))',
    '',
    ';; --- Expected pattern registry ---',
    '(= (expect-from (==> $context $expected) $context)',
    '   (expected $expected))',
    '',
    ';; --- Gap detector ---',
    '(= (gap? $expected (stv $f $c))',
    '   (if (< $c 0.1)',
    '     (gap-signal $expected strong)',
    '     (if (< $c 0.3)',
    '       (gap-signal $expected weak)',
    '       (no-gap $expected))))',
    '',
    ';; --- Resonance score ---',
    '(= (resonance $expected-stv $prior-expectation)',
    '   (let (stv $f $c) $expected-stv',
    '     (let $surprise (- $prior-expectation (+ (* $c (- $f 0.5)) 0.5))',
    '       (if (> $surprise 0.3)',
    '         (resonance-high $surprise)',
    '         (if (> $surprise 0.1)',
    '           (resonance-medium $surprise)',
    '           (resonance-low $surprise))))))',
    '',
    ';; --- Missing link detector ---',
    '(= (missing-link? $a-to-b $b-to-c)',
    '   (let (stv $f1 $c1) (second $a-to-b)',
    '     (let (stv $f2 $c2) (second $b-to-c)',
    '       (if (and (< $c1 0.1) (> $c2 0.5))',
    '         (missing-cause (first $a-to-b))',
    '         (chain-intact)))))',
    '',
    ';; --- Curiosity generator ---',
    '(= (curiosity-target (resonance-high $score) $domain)',
    '   (explore $domain $score))',
    '(= (curiosity-target (resonance-medium $score) $domain)',
    '   (note $domain $score))',
    '(= (curiosity-target (resonance-low $score) $domain)',
    '   (ignore))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates/lib_resonance.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
