import os
os.makedirs('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates', exist_ok=True)
lines = [
    ';; lib_ethical_grounding.metta -- ClarityClaw ethical reasoning layer',
    ';; Grounds decisions in value-weighted truth evaluation',
    ';; Pure MeTTa, no Python',
    '',
    ';; --- Type declarations ---',
    '(: ethical-weight Type)',
    '(: value-alignment Type)',
    '(: harm-potential (-> Atom Atom Number))',
    '(: agency-check (-> Atom Atom))',
    '(: value-conflict? (-> Atom Atom Atom))',
    '(: ethical-gate (-> Atom Atom Atom))',
    '(: reversibility (-> Atom Atom))',
    '',
    ';; --- Harm potential estimator ---',
    '(= (harm-potential $action (stv $f $c))',
    '   (if (and (> $f 0.7) (> $c 0.5))',
    '     (harm-high (* $f $c))',
    '     (if (> $f 0.4)',
    '       (harm-moderate (* $f $c))',
    '       (harm-low (* $f $c)))))',
    '',
    ';; --- Agency preservation check ---',
    '(= (agency-check $action)',
    '   (if (replaces-human-choice $action)',
    '     (agency-violation $action)',
    '     (agency-preserved $action)))',
    '',
    ';; --- Value conflict detector ---',
    '(= (value-conflict? (stv $f1 $c1) (stv $f2 $c2))',
    '   (let $dist (+ (abs (- $f1 $f2)) (abs (- $c1 $c2)))',
    '     (if (> $dist 0.6)',
    '       (conflict-strong $dist)',
    '       (if (> $dist 0.3)',
    '         (conflict-mild $dist)',
    '         (aligned)))))',
    '',
    ';; --- Ethical gate: only pass if harm is low and agency preserved ---',
    '(= (ethical-gate $action (stv $f $c))',
    '   (let $harm (harm-potential $action (stv $f $c))',
    '     (let $agency (agency-check $action)',
    '       (if (and (== $harm (harm-low $_)) (== $agency (agency-preserved $_)))',
    '         (proceed $action)',
    '         (pause-and-evaluate $action $harm $agency)))))',
    '',
    ';; --- Reversibility classifier ---',
    '(= (reversibility $action)',
    '   (if (irreversible-skill $action)',
    '     (irreversible $action)',
    '     (reversible $action)))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates/lib_ethical_grounding.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
