lines = [
    ';; lib_goal_memory.metta -- Goal-memory integration with revision accumulator',
    ';; Enables cross-cycle learning by revising stored goal confidence on new evidence',
    '',
    ';; --- Type declarations ---',
    '(: GoalRecord Type)',
    '(: UpdatedGoal Type)',
    '(: mk-goal (-> Atom Number Number GoalRecord))',
    '(: update-goal (-> GoalRecord Number Number UpdatedGoal))',
    '(: goal-status (-> GoalRecord Atom))',
    '',
    ';; --- Update goal with new evidence via NAL revision ---',
    '(= (update-goal (mk-goal $name $f_old $c_old) $f_new $c_new)',
    '   (let $w1 (* $c_old (- 1.0 $c_new))',
    '     (let $w2 (* $c_new (- 1.0 $c_old))',
    '       (let $wsum (+ $w1 $w2)',
    '         (let $f_rev (if (< $wsum 0.001) (* 0.5 (+ $f_old $f_new)) (/ (+ (* $f_old $w1) (* $f_new $w2)) $wsum))',
    '           (let $c_rev (- (+ $c_old $c_new) (* $c_old $c_new))',
    '             (mk-goal $name $f_rev $c_rev)))))))',
    '',
    ';; --- Goal status based on revised confidence ---',
    '(= (goal-status (mk-goal $name $f $c))',
    '   (if (< $c 0.3) (status $name dormant)',
    '     (if (< $f 0.4) (status $name failing)',
    '       (if (< $f 0.7) (status $name progressing)',
    '         (status $name thriving)))))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_goal_memory.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
