lines = [
    ';; lib_curiosity.metta -- Self-directed goal generation from epistemic gaps',
    ';; Connects gap detection to goal formation to priority ranking',
    '',
    ';; --- Type declarations ---',
    '(: EpistemicGap Type)',
    '(: CuriositySignal Type)',
    '(: GoalCandidate Type)',
    '(: PrioritizedGoal Type)',
    '(: detect-gap (-> Atom EpistemicGap))',
    '(: gap-to-signal (-> EpistemicGap CuriositySignal))',
    '(: signal-to-goal (-> CuriositySignal GoalCandidate))',
    '(: rank-goal (-> GoalCandidate GoalCandidate PrioritizedGoal))',
    '(: aligned? (-> GoalCandidate Atom Bool))',
    '(: curiosity-loop (-> Atom PrioritizedGoal))',
    '',
    ';; --- Gap detection: low confidence triggers curiosity ---',
    '(= (detect-gap (stv $f $c))',
    '   (if (< $c 0.3) (gap blind-spot (stv $f $c))',
    '     (if (< $c 0.5) (gap weak-zone (stv $f $c))',
    '       (gap none (stv $f $c)))))',
    '',
    ';; --- Gap to curiosity signal ---',
    '(= (gap-to-signal (gap blind-spot $stv))',
    '   (curiosity high $stv))',
    '(= (gap-to-signal (gap weak-zone $stv))',
    '   (curiosity medium $stv))',
    '(= (gap-to-signal (gap none $stv))',
    '   (curiosity low $stv))',
    '',
    ';; --- Signal to goal candidate ---',
    '(= (signal-to-goal (curiosity high $stv))',
    '   (goal-candidate urgent-exploration $stv))',
    '(= (signal-to-goal (curiosity medium $stv))',
    '   (goal-candidate scheduled-inquiry $stv))',
    '',
    ';; --- Rank by lowest confidence first (biggest gap = highest priority) ---',
    '(= (rank-goal (goal-candidate $t1 (stv $f1 $c1)) (goal-candidate $t2 (stv $f2 $c2)))',
    '   (if (< $c1 $c2) (prioritized $t1 $t2) (prioritized $t2 $t1)))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_curiosity.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
