lines = [
    ';; lib_temporal_decay.metta -- Goal freshness and staleness modeling',
    ';; Models confidence decay over time for unattended goals',
    '',
    ';; --- Type declarations ---',
    '(: FreshnessScore Type)',
    '(: StalenessSignal Type)',
    '(: DecayRate Type)',
    '(: freshness (-> Number Number FreshnessScore))',
    '(: staleness-check (-> FreshnessScore StalenessSignal))',
    '(: apply-decay (-> Number Number Number))',
    '',
    ';; --- Decay rate by domain ---',
    '(= (decay-rate empirical) 0.15)',
    '(= (decay-rate self-referential) 0.10)',
    '(= (decay-rate structural) 0.03)',
    '',
    ';; --- Apply decay: original-conf times 1 minus rate ---',
    '(= (apply-decay $conf $rate)',
    '   (* $conf (- 1.0 $rate)))',
    '',
    ';; --- Freshness from age and confidence ---',
    '(= (freshness $age $conf)',
    '   (fresh-score (* $conf (- 1.0 (* $age 0.1)))))',
    '',
    ';; --- Staleness check ---',
    '(= (staleness-check (fresh-score $s))',
    '   (if (< $s 0.2) (stale urgent-refresh)',
    '     (if (< $s 0.5) (stale refresh-soon)',
    '       (stale none))))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_temporal_decay.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
