lines = [
    ';; lib_metacognition.metta -- Self-monitoring and reasoning health tracking',
    ';; Monitors chain confidence, detects decay, generates maintenance goals',
    '',
    ';; --- Type declarations ---',
    '(: ChainHealth Type)',
    '(: DecaySignal Type)',
    '(: MaintenanceGoal Type)',
    '(: HealthStatus Type)',
    '(: assess-chain (-> Atom Atom ChainHealth))',
    '(: detect-decay (-> ChainHealth ChainHealth DecaySignal))',
    '(: decay-to-goal (-> DecaySignal MaintenanceGoal))',
    '(: health-status (-> Number HealthStatus))',
    '',
    ';; --- Health status by confidence ---',
    '(= (health-status $c)',
    '   (if (< $c 0.2) (status critical)',
    '     (if (< $c 0.5) (status degraded)',
    '       (status healthy))))',
    '',
    ';; --- Assess chain health from truth value ---',
    '(= (assess-chain $term (stv $f $c))',
    '   (chain-health $term (health-status $c) (stv $f $c)))',
    '',
    ';; --- Detect decay between two assessments ---',
    '(= (detect-decay (chain-health $t (status degraded) $stv1) (chain-health $t (status healthy) $stv2))',
    '   (decay $t from-healthy-to-degraded $stv1))',
    '(= (detect-decay (chain-health $t (status critical) $stv1) (chain-health $t (status degraded) $stv2))',
    '   (decay $t from-degraded-to-critical $stv1))',
    '(= (detect-decay (chain-health $t (status critical) $stv1) (chain-health $t (status healthy) $stv2))',
    '   (decay $t from-healthy-to-critical $stv1))',
    '',
    ';; --- Decay triggers maintenance goal ---',
    '(= (decay-to-goal (decay $t from-healthy-to-degraded $stv))',
    '   (maintenance-goal reinforce $t $stv))',
    '(= (decay-to-goal (decay $t from-degraded-to-critical $stv))',
    '   (maintenance-goal urgent-repair $t $stv))',
    '(= (decay-to-goal (decay $t from-healthy-to-critical $stv))',
    '   (maintenance-goal emergency-rebuild $t $stv))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_metacognition.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
