lines = [
    ';; lib_autocatalytic_cycle.metta -- Self-sustaining reasoning loop',
    ';; Formalizes the detect-prioritize-schedule-decay-redetect cycle',
    '',
    ';; --- Type declarations ---',
    '(: CyclePhase Type)',
    '(: CycleState Type)',
    '(: cycle-step (-> Atom Atom CyclePhase))',
    '(: run-cycle (-> Number Number Number CycleState))',
    '',
    ';; --- Phase transitions ---',
    '(= (cycle-step detect $conf)',
    '   (if (< $conf 0.3) (phase generate blind-spot) (phase assess $conf)))',
    '',
    '(= (cycle-step assess $conf)',
    '   (if (< $conf 0.5) (phase prioritize degraded) (phase maintain $conf)))',
    '',
    '(= (cycle-step prioritize $label)',
    '   (phase schedule $label))',
    '',
    '(= (cycle-step schedule $label)',
    '   (phase execute $label))',
    '',
    '(= (cycle-step execute $label)',
    '   (phase decay $label))',
    '',
    ';; --- Full cycle from conf and age ---',
    '(= (run-cycle $conf $age $rate)',
    '   (let $fresh (* $conf (- 1.0 (* $age $rate)))',
    '     (let $phase (cycle-step detect $fresh)',
    '       (cycle-result $fresh $phase))))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_autocatalytic_cycle.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
