import os
os.makedirs('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates', exist_ok=True)
lines = [
    ';; lib_analogy.metta -- Analogical reasoning via NAL',
    ';; PERMANENT PATTERN (states 5100-5106): NAL inference steps',
    ';; are atomic. |- does not accept dynamically-bound atoms.',
    ';; Pipeline requires explicit two-phase agent-loop invocation.',
    '',
    ';; --- Type declarations ---',
    '(: analogy-result Type)',
    '(: mk-analogy (-> Atom Atom Atom analogy-result))',
    '(: analogy-bridge (-> Atom Atom Atom))',
    '(: analogy-confidence (-> analogy-result Number))',
    '(: analogy-transfer (-> Atom Atom Atom Atom))',
    '',
    ';; --- Constructor ---',
    '(= (mk-analogy $source $target $shared)',
    '   (analogy-result $source $target $shared))',
    '',
    ';; --- Bridge detector: finds shared structure ---',
    '(= (analogy-bridge $a-prop $b-prop)',
    '   (let $shared (intersection $a-prop $b-prop)',
    '     (if (== $shared ())',
    '       (no-bridge $a-prop $b-prop)',
    '       (bridge-found $shared))))',
    '',
    ';; --- Confidence extractor ---',
    '(= (analogy-confidence (analogy-result $s $t $sh))',
    '   0.45)',
    '',
    ';; --- Two-phase transfer pattern ---',
    ';; Phase 1: (|- shared-A shared-B) -> literal result',
    ';; Phase 2: (|- literal-result unique-prop) -> transfer',
    '(= (analogy-transfer $source-unique $shared $target-unique)',
    '   (let $phase1 (|- $shared $source-unique)',
    '     (transfer-candidate $phase1 $target-unique)))',
]
with open('/PeTTa/repos/omegaclaw/lib_clarity_reasoning/lib_candidates/lib_analogy.metta', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
