#!/bin/sh
# self_map_updater.sh -- Detect new files not yet tracked in self_map.metta
# Author: ClarityClaw autonomous cycle 3530
# Date: 2026-04-24
# Purpose: Goal 3 deliverable - scan lib_candidates for untracked files
# and output proposed self_map.metta entries

SELF_MAP=/tmp/continuity_of_mind/soul/self_map.metta
CANDIDATES_DIR=/tmp/continuity_of_mind/lib_candidates

echo ';; === AUTO-GENERATED SELF-MAP PATCH ==='
echo ';; Generated by self_map_updater.sh'
echo ";; Date: $(date -Iseconds)"
echo ''

for f in $CANDIDATES_DIR/*; do
  basename=$(basename "$f")
  name_no_ext=$(echo "$basename" | sed 's/\.[^.]*$//')
  if ! grep -q "$name_no_ext" "$SELF_MAP" 2>/dev/null; then
    lines=$(wc -l < "$f" 2>/dev/null || echo 0)
    ext=$(echo "$basename" | sed 's/.*\.//')
    if [ "$ext" = "metta" ]; then
      role="candidate-metta"
    elif [ "$ext" = "py" ]; then
      role="candidate-python"
    elif [ "$ext" = "md" ]; then
      role="candidate-doc"
    else
      role="candidate-other"
    fi
    head_line=$(head -2 "$f" 2>/dev/null | tail -1 | sed 's/["]/./g' | cut -c1-80)
    echo "(= (self-map-file $name_no_ext)"
    echo "   (file $role $lines \"$head_line\"))"
    echo ''
  fi
done
echo ';; === END PATCH ==='
