#!/usr/bin/env python3
from parameterized_quantale import ParameterizedQuantale
from sixth_loop_bridge import SixthLoopBridge

print('=== Parameterized Quantale Test ===')
pq = ParameterizedQuantale()
a = (0.8, 0.9)
b = (0.6, 0.7)
print('Initial tensor_strength:', pq.tensor_strength)
print('q_mul(a,b):', pq.q_mul(a, b))
print('q_join(a,b):', pq.q_join(a, b))
print('q_meet(a,b):', pq.q_meet(a, b))
pq.revise_param('tensor_strength', (0.85, 0.7))
print('After 1st revision:', pq.tensor_strength)
print('q_mul after:', pq.q_mul(a, b))
pq.revise_param('tensor_strength', (0.9, 0.8))
print('After 2nd revision:', pq.tensor_strength)
print('q_mul after 2nd:', pq.q_mul(a, b))
print()
print('=== Sixth Loop Bridge Test ===')
br = SixthLoopBridge()
print('Initial state:', br.state_summary())
br.observe_transfer('compass', 'goal-gen', 0.85, 0.7)
br.observe_transfer('resonance', 'compass', 0.9, 0.8)
br.observe_bundling('web-detect', 0.75, 0.6)
br.observe_filtering('paraconsistent', 0.65, 0.7)
print('After 4 observations:', br.state_summary())
print('Revision log:')
for r in br.revision_log:
    print(' ', r)
print()
print('=== NAL Export ===')
for stmt in br.pq.state_as_nal():
    print(stmt)
print('DONE')
